---
version: '3.7'
services:
  pfm-riffdata:
    image: 'ghcr.io/rifflearning/riff-server/riffdata:3.0.0'
    hostname: pfm-riffdata
    depends_on:
      - pfm-riffdata-db
    ports:
      - '3000:3000'

  pfm-riffdata-db:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - pfm-riffdata-db-data:/data/db
      - pfm-riffdata-db-configdb:/data/configdb

  pfm-redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - pfm-redis-data:/data

volumes:
  pfm-riffdata-db-data:
  pfm-riffdata-db-configdb:
  pfm-redis-data:

