---
version: '3.7'
services:
  pfm-riffcollector:
    image: 'ghcr.io/rifflearning/riffcollector:2.0.0'
    hostname: pfm-riffcollector
    depends_on:
      - pfm-riffcollector-db
    ports:
      - '3000:3000'

  pfm-riffcollector-db:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - pfm-riffcollector-db-data:/data/db
      - pfm-riffcollector-db-configdb:/data/configdb

  pfm-redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - pfm-redis-data:/data

volumes:
  pfm-riffcollector-db-data:
  pfm-riffcollector-db-configdb:
  pfm-redis-data:

