---
version: '3.7'
services:
  pfm-riffdata:
    image: 'rifflearning/riffdata:dev'
    build:
      context: ${RIFF_SERVER_PATH-../riff-server}/docker
      dockerfile: Dockerfile-dev
      args:
        NODE_VER: 12
        PORT: 3000
    ports:
      - '3000:3000'
    volumes:
      - ${RIFF_SERVER_PATH-../riff-server}:/app

