---
version: '3.7'
services:
  pfm-riffcollector:
    image: 'rifflearning/riffcollector:dev'
    build:
      context: ${RIFFCOLLECTOR_PATH-../riffcollector}
      dockerfile: Dockerfile
      target: dev
      args:
        NODE_VER: 16
        PORT: 3000
    ports:
      - '3000:3000'
    volumes:
      - ${RIFFCOLLECTOR_PATH-../riffcollector}:/app
